struct State {
    long long count; // How many valid suffixes exist down this path?
    long long sum;   // What is the total property sum generated BY those suffixes?
};

// Inside the recursive step for placing digit 'd':
State current_transition;
current_transition.count = next_state.count;

// The core mathematical engine of the pattern:
current_transition.sum = (next_state.count * property_at_current_digit) + next_state.sum;